[package]
name = "pipes-and-rust"
version = "0.1.0"
authors = ["simon <simon@simonscode.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "0.9.1"
